name: CI_pandoc2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex
      - name: Generate HTML and PDFs
        run: |
          mkdir -p .public/pdf
          cp -r * .public
          for file in .public/*.md; do
            pandoc "$file" --embed-resources --standalone --css=style.css --metadata title="Marin Belvèze" --extract-media=./images -o "${file%.*}.html"
            pandoc "$file" --embed-resources --standalone --css=style.css --metadata title="Marin Belvèze" --extract-media=./images --pdf-engine=xelatex --listings -o ".public/pdf/$(basename "${file%.*}").pdf"
          done
          mv .public public
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: public-site
          path: public

      - name: Deploy    # pour déployer le site depuis la branche gh-pages (https://nom_utilisateur/github.io/repo)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.publish_token }} # nécessite la création d'un token (ici : https://github.com/settings/tokens ) avec les permissions nécessaires (contents:write pour un repo public) ; dans le repository 
          # suivre les instructions ci-dessous : 
          # Go to your repo → Settings → Secrets and variables → Actions
          # Click New repository secret
          # Name it something like publish_token
          # Paste your personal access token (here the hash corresponding to publish_token)


          publish_dir: ./public

